repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args: [--max-line-length=120]
    -   id: double-quote-string-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.761'
    hooks:
    -   id: mypy
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
    -   id: reorder-python-imports
